services:
    traefik:
        image: traefik:v3.2
        container_name: traefik
        restart: always
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 1
