FROM ldez/traefik-certs-dumper:v2.7.4

WORKDIR /data
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/bin/traefik-certs-dumper"]

RUN apk --no-cache add jq

COPY docker/dumper/entrypoint.dumper.sh /entrypoint.sh
