services:
    dumper:
        build:
            context: .
            dockerfile: docker/dumper/Dockerfile.dumper
        command: ["daemon"]
        network_mode: none
        volumes:
            - ./letsencrypt:/data
