services:
    docker-proxy:
        image: tecnativa/docker-socket-proxy
        restart: always
        environment:
            - CONTAINERS=1
        networks:
            - docker-proxy
        volumes:
            - docker-proxy-state:/var/lib/haproxy
            - /var/run/docker.sock:/var/run/docker.sock:ro

    traefik:
        command:
            - "--providers.docker.endpoint=tcp://docker-proxy:2375"
        depends_on:
            - docker-proxy
        environment:
            - DOCKER_HOST=docker-proxy:2375
        networks:
            - docker-proxy

networks:
    docker-proxy:

volumes:
    docker-proxy-state:
