services:
    traefik:
        command:
            - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
            - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

            - "--entrypoints.websecure.address=:443"
            - "--entrypoints.websecure.forwardedHeaders.insecure=true"
